services:
  discord-sso:
    image: ghcr.io/shopwarelabs/discord-bot:latest
    ports:
      - "8080:8080"
    volumes:
      - discord-sso-data:/app/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.discordbot.rule=Host(`discord.shopware.com`)"
      - "traefik.http.routers.discordbot.entrypoints=websecure"
      - "traefik.http.services.discordbot.loadbalancer.server.port=8080"
      - "traefik.http.routers.discordbot.service=discordbot"
      - "traefik.http.routers.discordbot.tls.certresolver=default"
    environment:
      # Microsoft OAuth
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - MICROSOFT_TENANT_ID=${MICROSOFT_TENANT_ID}
      
      # Discord
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - DISCORD_ROLE_ID=${DISCORD_ROLE_ID}
      
      # Server
      - PORT=${PORT:-8080}
      - BASE_URL=${BASE_URL:-http://localhost:8080}
      
      # Database
      - DATABASE_PATH=${DATABASE_PATH:-/app/data/discord-sso.db}
      
      # Gin mode
      - GIN_MODE=${GIN_MODE:-debug}
    
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  discord-sso-data:

networks:
  traefik:
    external: true
    name: core-services_default